repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.0  # Use the latest stable version
    hooks:
      - id: nbstripout
  # - repo: https://github.com/lorenzwalthert/pre-commit-hooks
  #   rev: v0.1.3
  #   hooks:
  #     - id: style-files
  #       #args: [--style_pkg = styler, --style_fun = tidyverse_style]
  #       files: '.*\.(R)'

